"""Evidently-based drift report generator.

Splits a list of :class:`~cpl_crop.monitoring.features.RequestFeatures`
records into a *reference* window (the first ``ref_size`` records) and
a *current* window (the rest) and runs a ``DataDriftPreset`` over the
numerical + categorical features.

The output is an HTML file you can open in a browser. Useful for the
hackathon demo: feed the system PlantVillage-style images first
(reference), then field photos (current), and the drift report
visualises the domain shift we already know is happening.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import pandas as pd

from cpl_crop.monitoring.features import CATEGORICAL_COLUMNS, NUMERICAL_COLUMNS

# Minimum rows we need on each side to compute meaningful drift stats.
# Below this we just write a "not enough data" HTML stub.
MIN_ROWS_PER_WINDOW = 5


def _records_to_frame(records: list[dict[str, Any]]) -> pd.DataFrame:
    """Convert raw JSONL dicts into a typed pandas DataFrame."""
    df = pd.DataFrame(records)
    if df.empty:
        return df
    for col in NUMERICAL_COLUMNS:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce")
    for col in CATEGORICAL_COLUMNS:
        if col in df.columns:
            df[col] = df[col].astype(str)
    return df


def _write_stub_report(out_path: Path, message: str) -> None:
    """Write a tiny self-contained HTML stub when we can't run drift."""
    html = f"""<!doctype html>
<html><head><meta charset='utf-8'><title>CPL Drift Report</title>
<style>body{{font-family:system-ui,sans-serif;max-width:720px;margin:60px auto;padding:24px;background:#fafafa;color:#222}}
h1{{margin-top:0}} .msg{{padding:16px;background:#fff;border-left:4px solid #f59e0b;border-radius:4px}}</style>
</head><body>
<h1>CPL Drift Report</h1>
<div class='msg'>{message}</div>
<p style='color:#666;font-size:.9em;margin-top:24px'>Generated by cpl_crop.monitoring.drift</p>
</body></html>
"""
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(html, encoding="utf-8")


def generate_drift_report(
    records: list[dict[str, Any]],
    out_path: Path,
    ref_size: int = 20,
) -> dict[str, Any]:
    """Generate an Evidently drift HTML at ``out_path``.

    Returns a small status dict with row counts and the output path.
    """
    out_path = Path(out_path)
    df = _records_to_frame(records)

    if df.empty:
        _write_stub_report(out_path, "No records logged yet. Hit /predict-v2 a few times first.")
        return {"status": "empty", "ref_rows": 0, "cur_rows": 0, "out_path": str(out_path)}

    if len(df) < ref_size + MIN_ROWS_PER_WINDOW:
        _write_stub_report(
            out_path,
            (
                f"Not enough data for a drift report yet. "
                f"Have {len(df)} records, need at least {ref_size + MIN_ROWS_PER_WINDOW} "
                f"(first {ref_size} = reference, remaining \u2265 {MIN_ROWS_PER_WINDOW} = current)."
            ),
        )
        return {
            "status": "insufficient_data",
            "ref_rows": min(ref_size, len(df)),
            "cur_rows": max(0, len(df) - ref_size),
            "out_path": str(out_path),
        }

    ref_df = df.iloc[:ref_size].reset_index(drop=True)
    cur_df = df.iloc[ref_size:].reset_index(drop=True)

    # Imports are lazy so the runtime API doesn't pay evidently startup
    # cost unless drift is actually requested.
    from evidently import DataDefinition, Dataset, Report
    from evidently.presets import DataDriftPreset

    data_def = DataDefinition(
        numerical_columns=[c for c in NUMERICAL_COLUMNS if c in df.columns],
        categorical_columns=[c for c in CATEGORICAL_COLUMNS if c in df.columns],
    )
    ref_ds = Dataset.from_pandas(ref_df, data_definition=data_def)
    cur_ds = Dataset.from_pandas(cur_df, data_definition=data_def)

    report = Report([DataDriftPreset()])
    snapshot = report.run(reference_data=ref_ds, current_data=cur_ds)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    snapshot.save_html(str(out_path))

    return {
        "status": "ok",
        "ref_rows": len(ref_df),
        "cur_rows": len(cur_df),
        "out_path": str(out_path),
    }
